global using GamingStore.Api.Data;
global using GamingStore.Api.DTOs;
global using GamingStore.Api.Middleware;
global using GamingStore.Api.Models;
global using GamingStore.Api.Models.Entities;
global using GamingStore.Api.Repositories;
global using GamingStore.Api.Services;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
