// <auto-generated />
using System;
using GamingStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamingStore.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804151940_AddIdentityAuthentication")]
    partial class AddIdentityAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamingStore.Api.Models.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("13a7712c-7f0b-4cb3-b9b1-09db733c4c5c"),
                            CoverImageUrl = "/images/games/auralith-drift.webp",
                            CreatedAt = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chart a silent alien ocean beneath luminous mineral rings and uncover why they are falling.",
                            Price = 24.99m,
                            ReleaseDate = new DateOnly(2025, 11, 14),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "auralith-drift",
                            Title = "Auralith Drift"
                        },
                        new
                        {
                            Id = new Guid("54acfc5b-694a-42c3-a21c-98188f1cf0a6"),
                            CoverImageUrl = "/images/games/cindervolt-coliseum.webp",
                            CreatedAt = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Battle rival magnetic drones around a living forge where every power-up reshapes the arena.",
                            Price = 14.99m,
                            ReleaseDate = new DateOnly(2026, 3, 8),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "cindervolt-coliseum",
                            Title = "Cindervolt Coliseum"
                        },
                        new
                        {
                            Id = new Guid("ab18590a-11fd-4269-9909-11aa2df97688"),
                            CoverImageUrl = "/images/games/mosswick-and-mooncoin.webp",
                            CreatedAt = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Run a woodland curiosity shop where every enchanted object arrives with a story and a price.",
                            Price = 19.99m,
                            ReleaseDate = new DateOnly(2024, 9, 27),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "mosswick-and-mooncoin",
                            Title = "Mosswick & Mooncoin"
                        },
                        new
                        {
                            Id = new Guid("7e62c4f2-0f4d-4f70-a407-0efc39b18e01"),
                            CoverImageUrl = "/images/games/neon-orchard.webp",
                            CreatedAt = new DateTime(2026, 7, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Explore a cyberpunk orchard where glowing fruit, city drones, and lost signals point toward a buried secret.",
                            Price = 29.99m,
                            ReleaseDate = new DateOnly(2026, 5, 19),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "neon-orchard",
                            Title = "Neon Orchard"
                        },
                        new
                        {
                            Id = new Guid("9b7e98d8-1d43-4d30-890d-3bb57cbf2d02"),
                            CoverImageUrl = "/images/games/starfall-kitchen.webp",
                            CreatedAt = new DateTime(2026, 7, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cook under zero gravity, chase floating ingredients, and serve strange comfort food across a tiny starship route.",
                            Price = 17.99m,
                            ReleaseDate = new DateOnly(2025, 8, 7),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "starfall-kitchen",
                            Title = "Starfall Kitchen"
                        },
                        new
                        {
                            Id = new Guid("1f1e36aa-4a2f-4f5b-9c42-57235fc18d03"),
                            CoverImageUrl = "/images/games/iron-vale-rally.webp",
                            CreatedAt = new DateTime(2026, 7, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Drift armored cars through mountain switchbacks, industrial shortcuts, and weather-battered rally stages.",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(2026, 2, 12),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "iron-vale-rally",
                            Title = "Iron Vale Rally"
                        },
                        new
                        {
                            Id = new Guid("ca79ef4a-a356-4e9f-9d4e-759a3ee61c04"),
                            CoverImageUrl = "/images/games/rune-harbor.webp",
                            CreatedAt = new DateTime(2026, 7, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Defend a stormlit port with sea magic, rune lighthouses, and choices that decide which ships make it home.",
                            Price = 24.99m,
                            ReleaseDate = new DateOnly(2024, 12, 3),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "rune-harbor",
                            Title = "Rune Harbor"
                        },
                        new
                        {
                            Id = new Guid("b2074502-1057-463a-a90a-22a7a6db6a05"),
                            CoverImageUrl = "/images/games/velvet-circuit.webp",
                            CreatedAt = new DateTime(2026, 7, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Race anti-gravity bikes through luxury neon circuits where boost timing matters as much as clean lines.",
                            Price = 21.99m,
                            ReleaseDate = new DateOnly(2025, 4, 18),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "velvet-circuit",
                            Title = "Velvet Circuit"
                        },
                        new
                        {
                            Id = new Guid("ed51ad9d-e182-4b74-a24c-b7a7ff422d06"),
                            CoverImageUrl = "/images/games/tiny-titan-tactics.webp",
                            CreatedAt = new DateTime(2026, 7, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Command miniature mechs across tabletop battlefields where dice, blocks, and clever positioning rule the day.",
                            Price = 12.99m,
                            ReleaseDate = new DateOnly(2026, 1, 30),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "tiny-titan-tactics",
                            Title = "Tiny Titan Tactics"
                        },
                        new
                        {
                            Id = new Guid("63db3015-067e-4438-ae55-f7bb7603a207"),
                            CoverImageUrl = "/images/games/glass-planet-survey.webp",
                            CreatedAt = new DateTime(2026, 7, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Map crystal canyons, scan alien minerals, and keep your expedition calm when the planet starts answering back.",
                            Price = 27.99m,
                            ReleaseDate = new DateOnly(2025, 10, 22),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "glass-planet-survey",
                            Title = "Glass Planet Survey"
                        },
                        new
                        {
                            Id = new Guid("f8f50b0e-7d23-48a0-8527-dfef40ea7208"),
                            CoverImageUrl = "/images/games/ember-library.webp",
                            CreatedAt = new DateTime(2026, 7, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Solve warm, dangerous puzzles in an ancient library where every burning book remembers a different truth.",
                            Price = 16.99m,
                            ReleaseDate = new DateOnly(2024, 11, 9),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "ember-library",
                            Title = "Ember Library"
                        },
                        new
                        {
                            Id = new Guid("4cdb6a49-c2de-4b1c-8fbd-f6951620a609"),
                            CoverImageUrl = "/images/games/glacier-guild.webp",
                            CreatedAt = new DateTime(2026, 7, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gather a crew, craft in the ice, and build impossible machines before the glacier city shifts again.",
                            Price = 34.99m,
                            ReleaseDate = new DateOnly(2026, 6, 11),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "glacier-guild",
                            Title = "Glacier Guild"
                        },
                        new
                        {
                            Id = new Guid("a55be02c-f531-472f-a763-4598b470cb10"),
                            CoverImageUrl = "/images/games/midnight-parcel.webp",
                            CreatedAt = new DateTime(2026, 7, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deliver fragile packages across rain-soaked rooftops while rival couriers chase the same impossible route.",
                            Price = 9.99m,
                            ReleaseDate = new DateOnly(2025, 2, 25),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Slug = "midnight-parcel",
                            Title = "Midnight Parcel"
                        });
                });

            modelBuilder.Entity("GamingStore.Api.Models.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Sellers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            CreatedAt = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Independent seller focused on thoughtful PC games.",
                            Email = "studio@northbyte.local",
                            Name = "Northbyte Games"
                        });
                });

            modelBuilder.Entity("GamingStore.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d16f5fd-0e50-4e25-894c-5f2d5a767b7f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6a449dac-52cc-4d02-8581-c800bc5d6453",
                            CreatedAt = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alex.player@gamingstore.local",
                            EmailConfirmed = true,
                            FirstName = "Alex",
                            LastName = "Player",
                            LockoutEnabled = true,
                            NormalizedEmail = "ALEX.PLAYER@GAMINGSTORE.LOCAL",
                            NormalizedUserName = "ALEX.PLAYER@GAMINGSTORE.LOCAL",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7b1b31d7-ff8c-4eb9-aed3-0d205b169807",
                            TwoFactorEnabled = false,
                            UserName = "alex.player@gamingstore.local"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GamingStore.Api.Models.Entities.Game", b =>
                {
                    b.HasOne("GamingStore.Api.Models.Entities.Seller", "Seller")
                        .WithMany("Games")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GamingStore.Api.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GamingStore.Api.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingStore.Api.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GamingStore.Api.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamingStore.Api.Models.Entities.Seller", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
