// <auto-generated />
using System;
using GamingStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamingStore.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamingStore.Api.Models.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("13a7712c-7f0b-4cb3-b9b1-09db733c4c5c"),
                            CreatedAt = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A compact sci-fi strategy game about rebuilding a fleet after a failed jump.",
                            Price = 24.99m,
                            ReleaseDate = new DateOnly(2025, 11, 14),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Title = "Starfall Tactics"
                        },
                        new
                        {
                            Id = new Guid("54acfc5b-694a-42c3-a21c-98188f1cf0a6"),
                            CreatedAt = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fast local arena battles with simple controls and sharp item timing.",
                            Price = 14.99m,
                            ReleaseDate = new DateOnly(2026, 3, 8),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Title = "Pixel Forge Arena"
                        },
                        new
                        {
                            Id = new Guid("ab18590a-11fd-4269-9909-11aa2df97688"),
                            CreatedAt = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A shopkeeping adventure where every item has a story and a margin.",
                            Price = 19.99m,
                            ReleaseDate = new DateOnly(2024, 9, 27),
                            SellerId = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            Title = "Dungeon Ledger"
                        });
                });

            modelBuilder.Entity("GamingStore.Api.Models.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Sellers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("84aa2fc0-1089-47d2-8a50-82f4d6e1de5f"),
                            CreatedAt = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Independent seller focused on thoughtful PC games.",
                            Email = "studio@northbyte.local",
                            Name = "Northbyte Games"
                        });
                });

            modelBuilder.Entity("GamingStore.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d16f5fd-0e50-4e25-894c-5f2d5a767b7f"),
                            CreatedAt = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alex.player@gamingstore.local",
                            FirstName = "Alex",
                            LastName = "Player"
                        });
                });

            modelBuilder.Entity("GamingStore.Api.Models.Entities.Game", b =>
                {
                    b.HasOne("GamingStore.Api.Models.Entities.Seller", "Seller")
                        .WithMany("Games")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("GamingStore.Api.Models.Entities.Seller", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
